---
title: "ADS1 outline - Cronicas study"
author: "Josiah Kephart"
date: "October 4, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##Project outline

Cronicas is a study of household air pollution and clinical outcomes in Lima and Puno, Peru in 2014-2015. 

48 hour direct-reading measurements of PM2.5 and CO at one minute temporal resolution were taken in roughly 400 households in Lima (urban) and 400 households in Puno (rural) who used traditional, biomass stoves for cooking.

###Research question
How do levels of PM2.5 and CO compare among houses who use traditional cookstoves between urban and rural areas of Peru?

###Steps:

1. Process 1600 raw data files into tidy datasets
2. Create summary measures of pollutant levels over time
3. Conduct analysis comparing baseline pollution across geographic locations


###Progress this week
* Pulled in all CO data - added filename as column
```{add filename}
read_csv_filename <- function(filename){
  ret <- fread(filename, showProgress = T, autostart = 15)
  ret$Source <- filename #EDIT
  ret
}

testdata <- ldply(filename, read_csv_filename); 
```

* Found appx. 5% of data to be faulty

* Removed faulty data

* Created hourly average and hourly max summary statistics

```{hourly ave}
funs <- c("mean", "max")

sumdata <- testdata %>%
  group_by(hiddt) %>%
  summarise_at(vars(pm), funs) 
head(sumdata)

> head(sumdata)
# A tibble: 6 × 3
              hiddt        mean    max
              <chr>       <dbl>  <dbl>
1 222009_05Jun15_06 0.451000000  0.451
2 222009_05Jun15_07 9.253100000 77.100
3 222009_05Jun15_08 1.601733333 16.430
4 222009_05Jun15_09 0.003966667  0.031
5 222009_05Jun15_10 0.002083333  0.034
6 222009_05Jun15_11 0.013666667  0.286

```


###Goals for the next week
* Follow-up with PI about faulty data
* Read in CO data
* Create plan for additional analysis